FROM ubuntu:14.04
MAINTAINER Deeping <deeping@foxmail.com>

RUN apt-get update && apt-get install -y git openssh-server net-tools busybox locales

RUN locale-gen en_US.UTF-8

RUN mkdir /var/run/sshd

# create 'git' user
RUN groupadd -r git && useradd -r -m -s /bin/bash -g git git

# install gosu
#wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/1.17/gosu-amd64"
#wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/1.17/gosu-amd64.asc"
#RUN chmod +x /usr/local/bin/gosu

# install gitolite
RUN su - git -c 'git clone https://github.com/sitaramc/gitolite.git'
RUN chown -R git:git /home/git
RUN su - git -c 'mkdir ~/bin && mkdir ~/repositories \
	&& gitolite/install -to $HOME/bin'

# http://stackoverflow.com/questions/22547939/docker-gitlab-container-ssh-git-login-error
RUN sed -i '/session    required     pam_loginuid.so/d' /etc/pam.d/sshd

# Remove SSH host keys, so they will be generated by /docker-entrypoint.sh
RUN rm -f /etc/ssh/ssh_host_*

# Addind volume to repositories directory
VOLUME /home/git/repositories
#VOLUME /etc/ssh

# Entrypoint responsible for SSH host keys generation, and Gitolite data initialization
COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]

# Expose port 22 to access SSH
EXPOSE 22

# Default command is to run the SSH server
CMD ["/usr/sbin/sshd", "-D"]
